apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-app-deployment

# Specification of the desired behavior of the deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
      - name: story-app-container
        image: einav1206/kube-data:latest
        volumeMounts:
        - mountPath: /app/story
          name: story-volume
      volumes:
      # - name: story-volume
      #   emptyDir: {}
      - name: story-volume
        # hostPath:
        #   path: /data
        #   type: DirectoryOrCreate
        persistentVolumeClaim:
          claimName: story-pvc
          
